# Generated by Django 3.1 on 2020-10-14 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyqan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emer', models.CharField(max_length=50, null=True)),
                ('adresa', models.CharField(max_length=50, null=True)),
                ('logo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DyqanProdukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sasia', models.IntegerField(default=1)),
                ('dyqan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.dyqan')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=50, null=True)),
                ('emer', models.CharField(max_length=50, null=True)),
                ('img_src', models.CharField(max_length=255, null=True)),
                ('pershkrim', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porosite', models.ManyToManyField(to='shops.DyqanProdukt')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dyqanprodukt',
            name='produkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.produkt'),
        ),
        migrations.AddField(
            model_name='dyqan',
            name='produkte',
            field=models.ManyToManyField(through='shops.DyqanProdukt', to='shops.Produkt'),
        ),
        migrations.AlterUniqueTogether(
            name='dyqanprodukt',
            unique_together={('produkt', 'dyqan')},
        ),
    ]
