# Generated by Django 3.1 on 2020-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyqanprodukt',
            name='cmimi',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dyqanprodukt',
            name='sasia',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
