# Generated by Django 3.1 on 2020-10-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20201014_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyqanprodukt',
            name='cmimi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
