# Generated by Django 3.1 on 2020-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20201014_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyqanprodukt',
            name='cmimi',
            field=models.FloatField(null=True),
        ),
    ]
